# Generated by Django 5.1.1 on 2024-09-07 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='url')),
                ('named_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='named_url')),
                ('menu_name', models.CharField(max_length=50, verbose_name='menu_name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'db_table': 'menu_item',
                'ordering': ['order'],
            },
        ),
    ]
